// ==UserScript==
// @name         GC Tool: Bulk Password Reset (Selected Users)
// @namespace    local.gc.tools
// @version      1.0
// @description  Reset passwords for selected users on the Directory People page
// @grant        none
// ==/UserScript==

(function () {
  'use strict';

  async function run({ token, apiBase, orgInfo }) {
    await window.GCHelpers.waitForBody();

    const {
      createPanel,
      createProgress,
      createLogger,
      addReturnButton,
      safeApiFetch,
      dl,
      sleep,
      stamp
    } = window.GCHelpers;

    const content = createPanel('Bulk Password Reset', 540);

    content.innerHTML = `
      <div style="font-size:12px; line-height:1.45; margin-bottom:10px; color:#d0d0d0;">
        Go to the <b>Directory / People</b> page and select users using the native checkboxes.
        This tool will reset passwords only for the currently selected rows.
      </div>

      <div style="font-size:12px; line-height:1.45; margin-bottom:10px; color:#ffcc66;">
        Passwords generated by this tool are 24 characters long and include uppercase, lowercase,
        numbers, and special characters.
      </div>

      <label style="display:block; margin:8px 0;">
        <input type="checkbox" id="dryRun" checked />
        Dry Run (default)
      </label>

      <label style="display:block; margin:8px 0;">
        <input type="checkbox" id="exportPasswords" />
        Export plaintext password CSV
      </label>

      <div style="font-size:12px; color:#ffcc66; margin:8px 0 12px 0;">
        Plaintext passwords are intentionally excluded from the normal log and CSV output.
      </div>

      <button id="scanBtn" style="width:100%; padding:10px; margin-bottom:8px; background:#444; color:#fff; border:none; border-radius:5px; cursor:pointer;">
        Scan Selected Users
      </button>

      <button id="runBtn" style="width:100%; padding:10px; margin-bottom:10px; background:#0078d4; color:#fff; border:none; border-radius:5px; cursor:pointer;">
        Reset Selected Passwords
      </button>

      <div id="status" style="margin-top:10px; font-size:12px; color:#d0d0d0;">
        Ready.
      </div>

      <div id="preview" style="margin-top:10px; max-height:180px; overflow:auto; font-size:12px; color:#d0d0d0; background:#1f1f1f; border:1px solid #444; border-radius:5px; padding:8px;">
        No users scanned yet.
      </div>
    `;

    const bar = createProgress(content);
    const dryRunBox = content.querySelector('#dryRun');
    const exportPasswordsBox = content.querySelector('#exportPasswords');
    const scanBtn = content.querySelector('#scanBtn');
    const runBtn = content.querySelector('#runBtn');
    const statusEl = content.querySelector('#status');
    const previewEl = content.querySelector('#preview');

    function escapeHtml(value) {
      return String(value ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
    }

    function escapeCsv(value) {
      const s = String(value ?? '');
      if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
      return s;
    }

    function randomChar(chars) {
      const arr = new Uint32Array(1);
      crypto.getRandomValues(arr);
      return chars[arr[0] % chars.length];
    }

    function shuffle(array) {
      for (let i = array.length - 1; i > 0; i--) {
        const arr = new Uint32Array(1);
        crypto.getRandomValues(arr);
        const j = arr[0] % (i + 1);
        [array[i], array[j]] = [array[j], array[i]];
      }
      return array;
    }

    function generatePassword(length = 24) {
      const upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
      const lower = 'abcdefghijkmnopqrstuvwxyz';
      const numbers = '23456789';
      const special = '!@#$%^&*()-_=+[]{}.?';
      const all = upper + lower + numbers + special;

      const chars = [
        randomChar(upper),
        randomChar(lower),
        randomChar(numbers),
        randomChar(special)
      ];

      while (chars.length < length) {
        chars.push(randomChar(all));
      }

      return shuffle(chars).join('');
    }

   function getPeopleDocument() {
        const directMatch = document.querySelector('#directory-people-index table tbody');
        if (directMatch) return document;

        const adminFrame =
            document.querySelector('iframe[name="admin"]') ||
            document.querySelector('iframe#admin') ||
            document.querySelector('frame[name="admin"]') ||
            document.querySelector('frame#admin');

        if (adminFrame) {
            try {
            const adminDoc = adminFrame.contentDocument || adminFrame.contentWindow?.document;
            if (adminDoc?.querySelector('#directory-people-index table tbody')) {
                return adminDoc;
            }
            } catch (e) {
            console.warn('Could not access admin frame:', e);
            }
        }

        for (const frame of document.querySelectorAll('iframe, frame')) {
            try {
            const frameDoc = frame.contentDocument || frame.contentWindow?.document;
            if (frameDoc?.querySelector('#directory-people-index table tbody')) {
                return frameDoc;
            }
            } catch (e) {
            // ignore inaccessible frames
            }
        }

        return null;
        }
   
    
    function detectSelectedUsers() {
        const doc = getPeopleDocument();
        if (!doc) return [];

        const rows = Array.from(
            doc.querySelectorAll('#directory-people-index table tbody tr')
        );

        const users = [];
        const seen = new Set();

        for (const row of rows) {
            const checkbox = row.querySelector('input[type="checkbox"]');
            if (!checkbox) continue;

            const isChecked =
            checkbox.checked ||
            checkbox.matches(':checked') ||
            checkbox.getAttribute('checked') === 'checked';

            if (!isChecked) continue;

            const link = row.querySelector(
            'a[href*="#/directory/peopleV2/"], a[ng-href*="#/directory/peopleV2/"]'
            );
            if (!link) continue;

            const href = link.getAttribute('href') || link.getAttribute('ng-href') || '';
            const match = href.match(/\/directory\/peopleV2\/([0-9a-f-]{36})/i);
            if (!match) continue;

            const id = match[1];
            if (seen.has(id)) continue;
            seen.add(id);

            users.push({
            id,
            name: (link.textContent || '').trim() || 'Unknown User',
            email: (row.querySelector('td.email')?.textContent || '').trim()
            });
    }

    return users;
    }

    function renderPreview(users) {
      if (!users.length) {
        previewEl.innerHTML = 'No selected users found.';
        return;
      }

      previewEl.innerHTML = users
        .map(user => {
          const email = user.email ? ` - ${escapeHtml(user.email)}` : '';
          return `<div style="margin-bottom:4px;">${escapeHtml(user.name)}${email}<br><span style="color:#999;">${escapeHtml(user.id)}</span></div>`;
        })
        .join('');
    }

    async function verifyUser(user) {
      const resp = await safeApiFetch(`${apiBase}/api/v2/users/${encodeURIComponent(user.id)}`, {
        method: 'GET',
        headers: {
          Authorization: `Bearer ${token}`
        }
      });

      if (!resp.ok) {
        return {
          ok: false,
          error: (await resp.text()) || `HTTP ${resp.status}`
        };
      }

      const data = await resp.json();
      return {
        ok: true,
        user: {
          id: data.id,
          name: data.name || data.username || data.email || user.name || user.id,
          email: data.email || user.email || '',
          username: data.username || ''
        }
      };
    }

    async function resetPassword(userId, password) {
      const resp = await safeApiFetch(`${apiBase}/api/v2/users/${encodeURIComponent(userId)}/password`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ "newPassword": password })
      });

      if (!resp.ok) {
        throw new Error((await resp.text()) || `HTTP ${resp.status}`);
      }
    }

    function getOrgShortName() {
      return String(orgInfo?.shortName || orgInfo?.name || orgInfo?.id || 'org')
        .replace(/[^\w.-]+/g, '_');
    }

    function exportSensitivePasswordCsv(rows) {
      const filename = `${getOrgShortName()}_bulkPasswordReset_passwords_${stamp()}.csv`;
      const csv = rows.map(row => row.map(escapeCsv).join(',')).join('\n');
      dl(filename, csv, 'text/csv');
    }

scanBtn.onclick = () => {
  const doc = getPeopleDocument();

  if (!doc) {
    statusEl.textContent = 'Could not find the Directory / People table. Try opening the People page first.';
    previewEl.innerHTML = 'No accessible People table found.';
    return;
  }

  const rows = doc.querySelectorAll('#directory-people-index table tbody tr').length;
  const checkboxes = doc.querySelectorAll('#directory-people-index table tbody input[type="checkbox"]').length;
  const checked = Array.from(
    doc.querySelectorAll('#directory-people-index table tbody input[type="checkbox"]')
  ).filter(cb => cb.checked || cb.matches(':checked') || cb.getAttribute('checked') === 'checked').length;

  const users = detectSelectedUsers();

  statusEl.textContent =
    `Detected ${users.length} selected user(s). Rows: ${rows}, Checkboxes: ${checkboxes}, Checked: ${checked}.`;

  renderPreview(users);
};

    runBtn.onclick = async () => {
      const selectedUsers = detectSelectedUsers();
      const isDryRun = dryRunBox.checked;
      const exportPasswords = exportPasswordsBox.checked;

      if (!selectedUsers.length) {
        alert('No selected users found. Go to Directory / People and check one or more users first.');
        statusEl.textContent = 'No selected users found.';
        renderPreview([]);
        return;
      }

      renderPreview(selectedUsers);

      const confirmed = confirm(
        isDryRun
          ? `Dry run password reset for ${selectedUsers.length} selected user(s)?`
          : `WARNING: Live reset passwords for ${selectedUsers.length} selected user(s)?`
      );
      if (!confirmed) return;

      const logger = createLogger(
        orgInfo,
        'bulkPasswordResetSelectedUsers',
        isDryRun ? 'dryrun' : 'live'
      );

      const passwordRows = [['UserId', 'Name', 'Email', 'Username', 'GeneratedPassword']];
      let success = 0;
      let fail = 0;
      let skipped = 0;
      let done = 0;

      bar.update(0, selectedUsers.length);
      statusEl.textContent = `${isDryRun ? 'Running dry run' : 'Running live reset'} for ${selectedUsers.length} user(s)...`;

      for (const selected of selectedUsers) {
        try {
          const verify = await verifyUser(selected);

          if (!verify.ok) {
            skipped++;
            logger.add(`SKIPPED ${selected.name} (${selected.id}) - verify failed: ${verify.error}`);
            logger.addCSV(selected.name, selected.id, 'SKIPPED', `Verify failed: ${verify.error}`);
          } else {
            const user = verify.user;
            const password = generatePassword(24);

            if (isDryRun) {
              logger.add(`DRY RUN Would reset password for ${user.name} (${user.id})`);
              logger.addCSV(user.name, user.id, 'DRY_RUN', 'Password reset preview');
              passwordRows.push([user.id, user.name, user.email, user.username, password]);
            } else {
              await resetPassword(user.id, password);
              success++;
              logger.add(`SUCCESS Password reset for ${user.name} (${user.id})`);
              logger.addCSV(user.name, user.id, 'SUCCESS', 'Password reset');
              passwordRows.push([user.id, user.name, user.email, user.username, password]);
            }
          }
        } catch (err) {
          fail++;
          const msg = err?.message || String(err);
          logger.add(`FAIL ${selected.name} (${selected.id}) - ${msg}`);
          logger.addCSV(selected.name, selected.id, 'FAIL', msg);
          console.error('Bulk Password Reset error:', selected, err);
        }

        done++;
        bar.update(done, selectedUsers.length);
        await sleep(250);
      }

      logger.add(`Summary: success=${success}, fail=${fail}, skipped=${skipped}, total=${selectedUsers.length}`);
      logger.save();

      if (exportPasswords && passwordRows.length > 1) {
        exportSensitivePasswordCsv(passwordRows);
      }

      statusEl.textContent = `Completed. Success: ${success}, Failed: ${fail}, Skipped: ${skipped}, Total: ${selectedUsers.length}`;
    };

    addReturnButton(content);
  }

  window.registerGcTool({
    name: 'Bulk Password Reset',
    version: '1.0',
    run
  });
})();